// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mhwilds_api.Services;

#nullable disable

namespace mhwilds_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250523204029_AddSKillFieldToArmour")]
    partial class AddSKillFieldToArmour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mhwilds_api.Models.Armour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Armours");
                });

            modelBuilder.Entity("mhwilds_api.Models.Resistances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmourId")
                        .HasColumnType("integer");

                    b.Property<string>("Dragon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thunder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Water")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArmourId")
                        .IsUnique();

                    b.ToTable("Resistances");
                });

            modelBuilder.Entity("mhwilds_api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("mhwilds_api.Models.SkillRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmourId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArmourId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRanks");
                });

            modelBuilder.Entity("mhwilds_api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmourId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArmourId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("mhwilds_api.Models.Resistances", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", "Armour")
                        .WithOne("Resistances")
                        .HasForeignKey("mhwilds_api.Models.Resistances", "ArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armour");
                });

            modelBuilder.Entity("mhwilds_api.Models.SkillRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", "Armour")
                        .WithMany("Skills")
                        .HasForeignKey("ArmourId");

                    b.HasOne("mhwilds_api.Models.Skill", "Skill")
                        .WithMany("Ranks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armour");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mhwilds_api.Models.Slot", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", "Armour")
                        .WithMany("Slots")
                        .HasForeignKey("ArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armour");
                });

            modelBuilder.Entity("mhwilds_api.Models.Armour", b =>
                {
                    b.Navigation("Resistances")
                        .IsRequired();

                    b.Navigation("Skills");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("mhwilds_api.Models.Skill", b =>
                {
                    b.Navigation("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
