// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mhwilds_api.Services;

#nullable disable

namespace mhwilds_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.Property<int>("ArmoursId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("ArmoursId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("ArmourSkillRank");
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.Property<int>("CharmsId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("CharmsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CharmRankSkillRank");
                });

            modelBuilder.Entity("DecorationSkillRank", b =>
                {
                    b.Property<int>("DecorationsId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.HasKey("DecorationsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("DecorationSkillRank");
                });

            modelBuilder.Entity("mhwilds_api.Models.Armour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Armours");
                });

            modelBuilder.Entity("mhwilds_api.Models.Charm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Charms");
                });

            modelBuilder.Entity("mhwilds_api.Models.CharmRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharmId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharmId");

                    b.ToTable("CharmRanks");
                });

            modelBuilder.Entity("mhwilds_api.Models.Decoration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Decorations");
                });

            modelBuilder.Entity("mhwilds_api.Models.Resistances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmourId")
                        .HasColumnType("integer");

                    b.Property<int>("Dragon")
                        .HasColumnType("integer");

                    b.Property<int>("Fire")
                        .HasColumnType("integer");

                    b.Property<int>("Ice")
                        .HasColumnType("integer");

                    b.Property<int>("Thunder")
                        .HasColumnType("integer");

                    b.Property<int>("Water")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArmourId")
                        .IsUnique();

                    b.ToTable("Resistances");
                });

            modelBuilder.Entity("mhwilds_api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("mhwilds_api.Models.SkillRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRanks");
                });

            modelBuilder.Entity("mhwilds_api.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmourId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArmourId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("ArmourSkillRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", null)
                        .WithMany()
                        .HasForeignKey("ArmoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwilds_api.Models.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharmRankSkillRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.CharmRank", null)
                        .WithMany()
                        .HasForeignKey("CharmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwilds_api.Models.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DecorationSkillRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.Decoration", null)
                        .WithMany()
                        .HasForeignKey("DecorationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mhwilds_api.Models.SkillRank", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mhwilds_api.Models.CharmRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.Charm", "Charm")
                        .WithMany("Ranks")
                        .HasForeignKey("CharmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charm");
                });

            modelBuilder.Entity("mhwilds_api.Models.Resistances", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", "Armour")
                        .WithOne("Resistances")
                        .HasForeignKey("mhwilds_api.Models.Resistances", "ArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armour");
                });

            modelBuilder.Entity("mhwilds_api.Models.SkillRank", b =>
                {
                    b.HasOne("mhwilds_api.Models.Skill", "Skill")
                        .WithMany("Ranks")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("mhwilds_api.Models.Slot", b =>
                {
                    b.HasOne("mhwilds_api.Models.Armour", "Armour")
                        .WithMany("Slots")
                        .HasForeignKey("ArmourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armour");
                });

            modelBuilder.Entity("mhwilds_api.Models.Armour", b =>
                {
                    b.Navigation("Resistances");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("mhwilds_api.Models.Charm", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("mhwilds_api.Models.Skill", b =>
                {
                    b.Navigation("Ranks");
                });
#pragma warning restore 612, 618
        }
    }
}
